export PATH="/Users/gregpuccio/documents/flutter/bin:$PATH"
export PATH="$PATH:$HOME/documents/flutter/bin"
export PATH="$PATH:$HOME/.npm-global/bin:$PATH"
export PATH="$PATH:$HOME/.pub-cache/bin"
export PATH="$PATH:$HOME/Python/3.9/bin"
